INSERT INTO EMPLOYEES (id, EMAIL_ADDRESS,FIRST_NAME,LAST_NAME) VALUES (1, 'USA@gmail.com','ram','sagar');
INSERT INTO EMPLOYEES (id, EMAIL_ADDRESS,FIRST_NAME,LAST_NAME) VALUES (2, 'France@gmail.com','ddd','ddddeee');
INSERT INTO EMPLOYEES (id, EMAIL_ADDRESS,FIRST_NAME,LAST_NAME) VALUES (3, 'Brazil@gmail.com','ddd1','ddddeee1');
INSERT INTO EMPLOYEES (id, EMAIL_ADDRESS,FIRST_NAME,LAST_NAME) VALUES (4, 'Italy@gmail.com','ddd11','ddddeee111');
INSERT INTO EMPLOYEES (id, EMAIL_ADDRESS,FIRST_NAME,LAST_NAME) VALUES (5, 'Canada@gmail.com','11ddd','ddddsseee');